export const products = [
  {
    id: 'dragon-berry',
    name: 'Dragon Berry',
    brand: 'VapeLab',
    price: 29.9,
    stock: 12,
    flavor: 'Mora dragón',
    nicotine: '3%',
    puffs: '6000',
    image: 'https://images.unsplash.com/photo-1606144042614-b2417e99c4e3?auto=format&fit=crop&w=900&q=80',
    description: 'Perfil afrutado con toque dulce y final refrescante ideal para sesiones prolongadas.',
    category: 'Disposable',
    active: true,
  },
  {
    id: 'mint-ice',
    name: 'Mint Ice',
    brand: 'FrostLine',
    price: 24.5,
    stock: 7,
    flavor: 'Menta hielo',
    nicotine: '2%',
    puffs: '5000',
    image: 'https://images.unsplash.com/photo-1592833160427-2544a4aa83bf?auto=format&fit=crop&w=900&q=80',
    description: 'Sabor limpio, intenso y muy frío para quienes prefieren un golpe refrescante.',
    category: 'Disposable',
    active: true,
  },
  {
    id: 'citrus-vibe',
    name: 'Citrus Vibe',
    brand: 'Glow',
    price: 31.2,
    stock: 9,
    flavor: 'Cítrico',
    nicotine: '5%',
    puffs: '7000',
    image: 'https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?auto=format&fit=crop&w=900&q=80',
    description: 'Una mezcla vibrante de cítricos con cuerpo ligero y muy buena intensidad.',
    category: 'Nitro',
    active: true,
  },
  {
    id: 'candy-cloud',
    name: 'Candy Cloud',
    brand: 'CloudPop',
    price: 26.8,
    stock: 0,
    flavor: 'Caramelo',
    nicotine: '4%',
    puffs: '4500',
    image: 'https://images.unsplash.com/photo-1528747045269-390fe33c19f2?auto=format&fit=crop&w=900&q=80',
    description: 'Espectro dulce y envolvente para usuarios que buscan aromas más juguetones.',
    category: 'Pods',
    active: true,
  },
];

export const getProductById = (id) => products.find((product) => product.id === id);
